// filepath: /home/welli/Projects/book-api/requests/req.http
@uri = http://localhost
@port = 8080

###GET HEALTH CHECK
GET {{uri}}:{{port}}/api/v1/health 

###GET ALL BOOKS
GET {{uri}}:{{port}}/api/v1/books

###GET A BOOK BY ID
GET {{uri}}:{{port}}/api/v1/books/3


###Create A NEW BOOK
POST {{uri}}:{{port}}/api/v1/books
Content-Type: application/json

{
    "id" :3,
    "title": "Minfulness",
    "author": "Jon Kabat-Zinn",
    "year": 1990,
    "description": "A guide to mindfulness meditation"
    }

###Delete A BOOK
DELETE {{uri}}:{{port}}/api/v1/books/7


###Create user
POST {{uri}}:{{port}}/api/v1/user/create
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@test.com",
    "password": "testpassword",
    "role": "user"
}